# Configuration for block-injector

# Application settings
app:
  name: block-injector
  version: "0.1.0"
  health_check_interval_ms: 15000  # Reduced from 30s
  summary_interval_seconds: 30
  mongodb_url: "mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0&retryWrites=true"
  mongodb_database: "block_injector"
  # Source database for querying token and DAO addresses
  source_mongodb_url: "mongodb+srv://backend2-nonprod-rw:EEWzPhPn3nn3lciQA3Ds@be-app-2-nonprod.bynx8zy.mongodb.net"  # Update with your source DB URL
  source_mongodb_database: "db-aragon-sandbox"             # Update with your source DB name

# Chain configurations
chains:
  # Ethereum mainnet
  ethereum-mainnet:
    enabled: true
    rpc_url: "https://eth-mainnet.g.alchemy.com/v2/eUGUKiYPaR4MoXzI2D98xAHwc6aC9e7w"
    poll_interval_seconds: 6
    finality_wait_seconds: 30
    batch_size: 2000  # Processor will split into 500-block chunks automatically
    
  # Polygon mainnet
  polygon-mainnet:
    enabled: true
    rpc_url: "https://polygon-mainnet.g.alchemy.com/v2/eUGUKiYPaR4MoXzI2D98xAHwc6aC9e7w"
    poll_interval_seconds: 3
    finality_wait_seconds: 10
    batch_size: 2000  # Processor will split into 500-block chunks automatically

  # Arbitrum mainnet
  arbitrum-mainnet:
    enabled: true
    rpc_url: "https://arb-mainnet.g.alchemy.com/v2/eUGUKiYPaR4MoXzI2D98xAHwc6aC9e7w"
    poll_interval_seconds: 3
    finality_wait_seconds: 10
    batch_size: 2000  # Processor will split into 500-block chunks automatically

  # Ethereum Sepolia - properly configured
  ethereum-sepolia:
    enabled: true
    rpc_url: "https://eth-sepolia.g.alchemy.com/v2/eUGUKiYPaR4MoXzI2D98xAHwc6aC9e7w"
    poll_interval_seconds: 6        # Respect this value, don't override!
    finality_wait_seconds: 15
    batch_size: 2000  # Processor will split into 500-block chunks automatically
  
  # Base mainnet
  base-mainnet:
    enabled: true
    rpc_url: "https://base-mainnet.g.alchemy.com/v2/eUGUKiYPaR4MoXzI2D98xAHwc6aC9e7w"
    poll_interval_seconds: 3
    finality_wait_seconds: 10
    batch_size: 2000  # Processor will split into 500-block chunks automatically

  optimism-mainnet:
    enabled: true
    rpc_url: "https://opt-mainnet.g.alchemy.com/v2/eUGUKiYPaR4MoXzI2D98xAHwc6aC9e7w"
    poll_interval_seconds: 3
    finality_wait_seconds: 10
    batch_size: 2000 

# Event topics to monitor with human-readable signatures
topics:
  "0x8cc06643d6cbee78b006d2df2db4d2487b69dd64bb2c96088280fb29dd93a0b2": "PluginRepoRegistered(string subdomain, address pluginRepo)"
  "0xbc0b11fe649bb4d67c7fb40936163e5423f45c3ae83fbd8f8f8c75e1a3fa97af": "DAORegistered(address dao, address creator, string subdomain)"
  "0x8ea69cee01fd9fc24e6b9614ea0896c5a1eac8fd8aba383285248cd0e1d8503a": "InstallationPrepared(address sender, address dao, bytes32 preparedSetupId, address pluginSetupRepo, tuple versionTag, bytes data, address plugin, tuple preparedSetupData)"
  "0x74e616c7264536b98a5ec234d051ae6ce1305bf05c85f9ddc112364440ccf129": "InstallationApplied(address dao, address plugin, bytes32 preparedSetupId, bytes32 appliedSetupId)"
  "0x24565610ddf61ee73e8501d7f0454657c71f5944882f5c586d7246bf43e13cda": "UpdateApplied(address dao, address plugin, bytes32 preparedSetupId, bytes32 appliedSetupId)"
  "0x3686138d92841c8549b2fe39fda23881fef6aa9b347352114c0869bf5af3e3f2": "UpdatePrepared(address sender, address dao, bytes32 preparedSetupId, address pluginSetupRepo, tuple versionTag, tuple setupPayload, tuple preparedSetupData, bytes initData)"
  "0xa0e5d4ce6420a0e7a5f0ac10c47b3a672fb661c11f5609bb21b68644d81e17aa": "UninstallationApplied(address dao, address plugin, bytes32 preparedSetupId)"
  "0x5fdcd271ff15db84cbc94365956df5504f6d756e111654144648433c11a44530": "UninstallationPrepared(address sender, address dao, bytes32 preparedSetupId, address pluginSetupRepo, tuple versionTag, tuple setupPayload, tuple[] permissions)"
  "0x7d8a9a57630acbcfb28eb55b1ce0ff7b3d0dc9edea594075a8a6af35278a4cf9": "MultisigSettingsUpdated(bool onlyListed, uint16 minApprovals)"
  "0xa8a18d06ddd19f24a872740e3d364c86f62be25f7154525dda18ef07fda46f3e": "VotingSettingsUpdated(uint8 votingMode, uint32 supportThreshold, uint32 minParticipation, uint64 minDuration, uint256 minProposerVotingPower)"
  "0x435d9e99466e98c43eea30339b592c89335a9cd4304822838938882df53308fe": "StagesUpdated(tuple[] stages)"
  "0xbfaa970a350cc4e6c21888b5c4b888e2750f035ce824e40cfc7dc5f07e3936c5": "ProposalResultReported(uint256 proposalId, uint16 stageId, address body)"
  "0x11ba20e083ffba533caf1d501ce171aa2acdc05a5601e4e473e449460b0718d8": "MembersAdded(address[] members)"
  "0x0ba413f7646035cae0a4ee999d676078fc8a763d1a36a8ef25e4c10f67d8615d": "MembersRemoved(address[] members)"
  "0xa6c1f8f4276dc3f243459e13b557c84e8f4e90b2e09070bad5f6909cee687c92": "ProposalCreated(uint256 proposalId, address creator, uint64 startDate, uint64 endDate, bytes metadata, tuple[] actions, uint256 allowFailureMap)"
  "0x712ae1383f79ac853f8d882153778e0260ef8f03b504e2866e0593e04d2b291f": "ProposalExecuted(uint256 proposalId)"
  "0x578c7050405154b6a8167f305908011ff85e3231eff1fbce2bbe95500b92f203": "ProposalCanceled(uint256 proposalId, uint16 stageId, address sender)"
  "0xc1d7dc1770290440bd536be5eca85bc1e54960c21ef0f9a838033941a7392d8d": "ProposalEdited(uint256 proposalId, uint16 stageId, address sender, bytes metadata, tuple[] actions)"
  "0xa21690322ce39bce6ee8416aefbe1e66cf767ff37e9db8f708a3c6cbbf17db9b": "ProposalAdvanced(uint256 proposalId, uint16 stageId, address sender)"
  "0x7b39c92a7e1a86e846edaeff6eba715a046352c596794c2a374269c126a99768": "Approved(uint256 proposalId, address approver)"
  "0xb83d25c6a5d258561330739951487acb4bd09ba5190b5d32c4f261817d906792": "VoteCast(uint256 proposalId, address voter, uint8 voteOption, uint256 votingPower)"
  "0xbb39ebb37e60fb5d606ffdb749d2336e56b88e6c88c4bd6513b308f643186eed": "MetadataSet(bytes metadata)"
  "0xdec2bacdd2f05b59de34da9b523dff8be42e5e38e818c82fdb0bae774387a724": "DelegateVotesChanged(address delegate, uint256 previousBalance, uint256 newBalance)"
  "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef": "Transfer(address from, address to, uint256 value)"
  "0x62c2c8e34665db7c56b2cabd7f5fb9702ccd352ffa8150147e450797e9f8e8f3": "NativeTokenDeposited(address sender, uint256 amount)"
  "0x0f579ad49235a8c1fd9041427e7067b1eb10926bbed380bf6fabc73e0e807644": "Granted(bytes32 permissionId, address here, address where, address who, address condition)"
  "0x3ca48185ec3f6e47e24db18b13f1c65b1ce05da1659f9c1c4fe717dda5f67524": "Revoked(bytes32 permissionId, address here, address where, address who)"
  "0x7162984403f6c73c8639375d45a9187dfd04602231bd8e587c415718b5f7e5f9": "Deposit(address depositor, uint256 tokenId, uint256 startTs, uint256 value, uint256 newTotalLocked)"
  "0xe08737ac48a1dab4b1a46c7dc9398bd5bfc6d7ad6fabb7cd8caa254de14def35": "Withdraw(address depositor, uint256 tokenId, uint256 value, uint256 ts, uint256 newTotalLocked)"
  "0xc50a7f0bdf88c216b2541b0bdea26f22305460e39ffc672ec1a7501732c5ba81": "MinDepositSet(uint256 minDeposit)"
  "0x11c29007060e964dd76773c12f776a14f50d668a156f0eb2c8b536e70c1bf183": "ExitQueued(uint256 tokenId, address holder, uint256 exitDate)"
  "0x3052536486f1a4ce9c6c86b3ff8d04497ceeacf20783ea15fb60ce5c2b131416": "MinLockSet(uint48 minLock)"
  "0xde8db7f1a4d061c24c5971661fff1d7434516c8a9108e77de4b700c952a3d8dd": "TokensDelegated(address sender, address delegatee, uint256[] tokenIds)"
  "0x79573056ed35bad9d99742a774057c03f82ef2d07e485b1fca4619e7f3ad664a": "TokensUndelegated(address sender, address delegatee, uint256[] tokenIds)"
